# Permalinks
permalink:           pretty

# Setup
title:               Nicole Semerano
tagline:             A Glimpse into My Data Science Blog
url:                 http://nicolesemerano.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nicole Semerano
  url:               http://www.linkedin.com/in/nicole-semerano/
  email:             nicole.semerano@yahoo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/nicolesemerano

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

theme: jekyll-theme-cayman
